import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-cream">
      <nav className="px-6 md:px-12 py-4 flex items-center justify-between border-b border-border">
        <Link href="/" className="font-display text-xl font-bold tracking-tight">
          Listing<span className="text-terracotta">Forge</span>
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 md:px-12 py-16">
        <h1 className="font-display text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-ink-faint mb-10">Last updated: March 6, 2026</p>

        <div className="space-y-8 text-sm text-ink-soft leading-relaxed">
          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using ListingForge (&quot;the Service&quot;), operated by ListingForge (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">2. Description of Service</h2>
            <p>ListingForge is an AI-powered platform that provides e-commerce listing generation, SEO analysis, product research, ad copy generation, and A/B testing tools. The Service uses artificial intelligence and third-party data sources to generate content and insights.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">3. Account Registration</h2>
            <p>You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must provide accurate and complete information when creating your account.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">4. Free Trial and Subscriptions</h2>
            <p>New users receive a 3-day free trial with access to all Growth features. After the trial period, you may continue with the free Starter plan or subscribe to the Growth plan. Subscriptions are billed monthly or annually through Stripe. You may cancel your subscription at any time through the billing page.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">5. Payments and Refunds</h2>
            <p>All payments are processed securely through Stripe. Subscription fees are non-refundable except as required by law. Upon cancellation, you will retain access to paid features until the end of your current billing period.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">6. AI-Generated Content</h2>
            <p>Content generated by the Service is provided as suggestions and starting points. You are responsible for reviewing, editing, and ensuring the accuracy of all generated content before use. We do not guarantee that generated content will be free of errors, unique, or suitable for any particular purpose.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">7. Data and Research</h2>
            <p>Product research data, trend analysis, and market insights are provided for informational purposes only. While we use real data sources including Google Trends, the analysis includes AI-generated estimates and should not be the sole basis for business decisions.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">8. Intellectual Property</h2>
            <p>You retain ownership of all content you input into the Service. Content generated by the Service for your use is licensed to you for commercial use. The Service itself, including its design, code, and branding, remains our intellectual property.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">9. Prohibited Use</h2>
            <p>You may not use the Service to generate content that is illegal, misleading, defamatory, or infringes on third-party rights. You may not attempt to reverse engineer the Service, abuse the free trial system, or create multiple accounts to circumvent usage limits.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">10. Limitation of Liability</h2>
            <p>The Service is provided &quot;as is&quot; without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service, including but not limited to lost profits, lost sales, or business interruption.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">11. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms. We will notify users of material changes via email or in-app notification.</p>
          </section>

          <section>
            <h2 className="font-display text-lg font-bold text-ink mb-3">12. Contact</h2>
            <p>For questions about these terms, contact us at <a href="mailto:support@listingforge.pro" className="text-terracotta hover:underline">support@listingforge.pro</a>.</p>
          </section>
        </div>
      </div>
    </div>
  );
}